#!/bin/bash

#
# Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

quit() {
    echo ${1}
    exit ${1}
}

[[ -f "/usr/lib/libindy.so" ]] || quit 1

[[ "$(which docker | wc -l)" -eq "1" ]] || quit 1

INDY_POOL=$(docker images --filter reference=indy_pool | sed '1,1d' | wc -l)
[[ "${INDY_POOL}" -eq "1" ]] || quit 1

INDY_POOL_NETWORK=$(docker network ls --filter name=indy_pool_network | sed '1,1d' | wc -l)
[[ "${INDY_POOL_NETWORK}" -eq "1" ]] || quit 1

PYTEST_PACKAGES=$(cat ${HOME}/Pipfile | awk '/\[packages\]/,0' | grep -P '(pytest)|(pytest-asyncio)' | wc -l)
[[ "${PYTEST_PACKAGES}" -eq "2" ]] || quit 1

quit 0
