#!/bin/bash

quit() {
    echo ${1}
    exit ${1}
}

[[ -f "/usr/lib/libindy.so" ]] || quit 1

[[ "$(which docker | wc -l)" -eq "1" ]] || quit 1

INDY_POOL=$(docker images --filter reference=indy_pool | sed '1,1d' | wc -l)
[[ "${INDY_POOL}" -eq "1" ]] || quit 1

INDY_POOL_NETWORK=$(docker network ls --filter name=indy_pool_network | sed '1,1d' | wc -l)
[[ "${INDY_POOL_NETWORK}" -eq "1" ]] || quit 1

DIR_PY35=$(eval echo "~$(logname)/venv/py35")
[[ -d "${DIR_PY35}" ]] || quit 1

quit 0
