@startuml
/'
Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'/

skinparam ParticipantPadding 20
skinparam BaloxPadding 20

title Verifier Agent On-Line Boot Sequence


box "Indy" #LightBlue
    participant "Ledger" as ledger
endbox
actor "Trust Anchor\nAgent" as tag
actor "Verifier\n(e.g., SRI)\nAgent" as sag

=== BOOTSTRAP ==
note over ledger, sag
    Node pool is open (verifier agent is on-line)
endnote

sag -> sag: call get_nym(did)
group get_nym() implements
    sag -> ledger: Look up own nym
    ledger --> sag: nym if present
end
alt Nym not present
    note over ledger, sag
        Trust anchor agent service wrapper API is up
    endnote
    sag -[#blue]> tag: call send_nym(did, verkey, alias, role)
    group send_nym() implements
        tag -[#blue]> ledger: send agent nym
        ledger --[#blue]> tag: agent nym
        tag --[#blue]> sag: agent nym
    end
end

@enduml
