@startuml
/'
Copyright 2017 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'/

title Class Diagram

class Wallet {
    -_seed
    +pool_name
    +base_name
    +name
    +num
    +handle
    +cfg_json
    +did
    +verkey
}

class NodePool {
    +name
    +genesis_txn_path
    +handle
    +open()
    +close()
}

class BaseAgent {
    +pool
    +wallet
    +did
    +verkey
    +open()
    +close()
    +get_nym()
    +get_schema()
    +get_endpoint()
}

class BaseListeningAgent {
    +host
    +port
    +agent_api_path
    +schema_cache
    -_vet_keys()
    -_schema_info()
    -_response_from_proxy()
    -_mro_dispatch()
    +send_endpoint()
    +get_claim_def()
    +process_post()
    +process_get_txn()
    +process_get_did()
}

class AgentRegistrar {
    +send_nym()
    +process_post()
}

class Origin {
    +send_schema()
    +process_post()
}

class Issuer {
    +send_claim_def()
    +create_claim()
    +process_post()
}

class HolderProver {
    -_master_secret
    +claim_req_json
    +send_claim_def()
    +create_claim()
    +create_master_secret()
    +store_claim_offer()
    +store_claim_req()
    +store_claim()
    +create_proof()
    +get_claims()
    +get_claim_by_claim_uuid()
    +reset_wallet()
    +process_post()
}

class Verifier {
    +verify_proof()
    +process_post()
}

class TrustAnchorAgent {
    +process_post()
}

class SRIAgent {
    +reset_wallet()
    +process_post()
}

class BCRegistrarAgent {
    +process_post()
}

class OrgBookAgent {
    +process_post()
}

BaseAgent "1" *-left- "1" NodePool
BaseAgent "1" *-right- "1" Wallet

BaseAgent <|-down- BaseListeningAgent
BaseListeningAgent <|-left- AgentRegistrar
BaseListeningAgent <|-left- Origin
BaseListeningAgent <|-right- Issuer
BaseListeningAgent <|-down- HolderProver
BaseListeningAgent <|-down- Verifier

AgentRegistrar <|-down- TrustAnchorAgent
Origin <|-down- TrustAnchorAgent

Issuer <|-right- SRIAgent
Verifier <|-down- SRIAgent
HolderProver <|- SRIAgent

Issuer <|- BCRegistrarAgent

HolderProver <|-down- OrgBookAgent

@enduml
