@startuml
/'
Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'/

title Class Diagram

class ErrorCode {
}

class VonAgentError {
    + error_code
    + message
}

class SchemaKey {
    origin_did
    name
    version
}

class SchemaCache {
    -_schema_key2schema
    -_seq_no2schema_key
    +__setitem__()
    +__getitem__()
    +contains()
    +index()
    +schema_key_for()
}

class Wallet {
    -_seed
    +pool
    +name
    +xtype
    +handle
    +did
    +verkey
    +cfg
    +auto_remove
    +creds
    +created
    -_seed2did()
}

class NodePool {
    +name
    +genesis_txn_path
    +handle
    +open()
    +close()
}

class _AgentCore {
    +pool
    +wallet
    +did
    +verkey
    +open()
    +close()
    +get_nym()
    +get_schema()
    +get_endpoint()
}

class _BaseAgent {
    +cfg
    -_response_from_proxy()
    -_mro_dispatch()
    +send_endpoint()
    +get_claim_def()
    +process_post()
    +process_get_txn()
    +process_get_did()
}

class AgentRegistrar {
    +send_nym()
    +process_post()
}

class Origin {
    +send_schema()
    +process_post()
}

class Issuer {
    +send_claim_def()
    +create_claim_offer()
    +create_claim()
    +process_post()
}

class HolderProver {
    -_master_secret
    +create_master_secret()
    +store_claim_req()
    +store_claim()
    +create_proof()
    +get_claims()
    +get_claim_by_referent()
    +reset_wallet()
    +process_post()
}

class Verifier {
    +verify_proof()
    +process_post()
}

class TrustAnchorAgent {
    +process_post()
}

class SRIAgent {
    +process_post()
}

class BCRegistrarAgent {
    +process_post()
}

class OrgBookAgent {
    +process_post()
}

VonAgentError "1" *-up- "1" ErrorCode
SchemaCache -left-> SchemaKey
_AgentCore -left-> SchemaKey

_AgentCore -up-> SchemaCache
_AgentCore "1" *-right- "1" Wallet
Wallet "1" *-up- "1" NodePool

_AgentCore <|-down- _BaseAgent
_BaseAgent <|-left- AgentRegistrar
_BaseAgent <|-left- Origin
_BaseAgent <|-right- HolderProver
_BaseAgent <|-right- Verifier

AgentRegistrar <|-down- TrustAnchorAgent
Origin <|-down- TrustAnchorAgent
Origin <|-down- Issuer

Issuer <|-down- SRIAgent
Verifier <|-down- SRIAgent

Issuer <|- BCRegistrarAgent

HolderProver <|-down- OrgBookAgent

@enduml
