@startuml
/'
Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'/

skinparam ParticipantPadding 20
skinparam BoxPadding 20

title Verification Sequence

box "Indy" #LightBlue
    participant "Ledger" as ledger
endbox

actor "Verifier\n(e.g., SRI)\nAgent" as sag
actor "Actuator" as ator

=== VERIFICATION SEQUENCE ==
ator -> sag: call verify_proof(proof_req, proof)
group verify_proof() implements
    loop each identifier in proof
        sag -> ledger: get schema
        ledger --> sag: schema
        sag -> ledger: get cred def
        ledger --> sag: cred def
        sag -> ledger: get rev reg def
        ledger --> sag: rev reg def
        sag -> ledger: get rev reg state
        ledger --> sag: rev reg state 
    end
    sag -> sag: verify proof
    sag -> ator: True or False
end

@enduml
