#!/bin/bash

#
# Copyright 2017 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [[ "${EUID}" -eq 0 ]]
then
    echo "Error: please run ${BASH_SOURCE[0]} as non-sudo"
    echo
    exit 1
fi

# python virtual environment (setup as non-sudo)
DIR_HOME=$(eval echo "~")
DIR_VENV="${DIR_HOME}/venv"
DIR_PY35="${DIR_VENV}/py35"

[[ -d "${DIR_VENV}" ]] || mkdir "${DIR_VENV}"
[[ -d "${DIR_PY35}" ]] || virtualenv -p /usr/bin/python3.5 "${DIR_PY35}"

source ${DIR_PY35}/bin/activate
pip install -U pytest
pip install -U pytest-asyncio
