#!/bin/bash

DIR_ROOT="$(realpath $(dirname ${BASH_SOURCE[0]}))"
DIR_FILES="${DIR_ROOT}/files"

# build docker image
INDY_POOL=$(docker images --filter reference=indy_pool | sed '1,1d' | wc -l)
if [[ "${INDY_POOL}" -eq "0" ]]
then
    docker build --build-arg pool_ip=10.0.0.2 -f "${DIR_FILES}/indy-pool.dockerfile" -t indy_pool .
fi

# build docker network
INDY_POOL_NETWORK=$(docker network ls --filter name=indy_pool_network | sed '1,1d' | wc -l)
if [[ "${INDY_POOL_NETWORK}" -eq "0" ]]
then
    docker network create --subnet 10.0.0.0/8 indy_pool_network
fi

# install libindy.so
cd "${DIR_FILES}"
tar -xpvzf libindy.so.tgz &> /dev/null
mv libindy.so /usr/lib/
